### ISSUE TITLE
DialogController.ok() or DialogController.cancel(); the modal does not close when calling from non-view model

### ISSUE THREAD

**Issue by m-andrew-albright** [aurelia/dialog#200] opened 2016-07-29 11:58 UTC
**I'm submitting a bug report**
- **Library Version:**
  1.0.0-beta.2.0.0

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  6.2.2
- **NPM Version:**
  3.9.5
- **JSPM OR Webpack AND Version**
  JSPM 0.16.39
- **Browser:**
  Chrome 51.0.2704.103 | Firefox 47.0 | Edge 25.10586.0.0
- **Language:**
  ESNext

**Current behavior:**

We had decided to wrap the usage of aurelia-dialog in an abstracted layer so that switching modals out later would only require one place to change any code out.  This mostly works, but calling `this.dialogController.ok()` or `this.dialogController.cancel()` results in the following error (stack trace is from this.dialogController.cancel() specifically):

```
lifecycle.js:10 Uncaught TypeError: Cannot read property 'canDeactivate' of undefined
    invokeLifecycle @ lifecycle.js:10
    close @ dialog-controller.js:46
    cancel @ dialog-controller.js:27
    cancel @ modal-controller.js:17
    cancelButtonClick @ add-user.js:42
    evaluate @ aurelia-binding.js:1570
    callSource @ aurelia-binding.js:4997
    (anonymous function) @ aurelia-binding.js:5021
    handleDelegatedEvent @ aurelia-binding.js:3210
```

**Expected/desired behavior:**

- **What is the expected behavior?**

The expected behavior is that the modal should not throw an error, and it should close.
- **What is the motivation / use case for changing the behavior?**

So that it works when wrapping the dialog-controller and dialog-service in an abstraction layer for ease of changing modal/dialog providers in the future.

**Comment by PWKad** [comment] 2016-08-13 03:56
Can you provide some code of what the wrapper looks like?

**Comment by m-andrew-albright** [comment] 2016-08-18 01:25
ModalController (wraps DialogController):

```
import { DialogController } from 'aurelia-dialog';

// This is the class that should be passed into any view that will live inside
// a modal.
export class ModalController {
  static inject = [DialogController];
  constructor(dialogController) {
    this.dialogController = dialogController;
    this.settings = dialogController.settings;
  }

  ok(model) {
    return this.dialogController.ok(model);
  }

  cancel(model) {
    return this.dialogController.cancel(model);
  }
}
```

ModalService (wraps DialogService):
```
import { DialogService } from 'aurelia-dialog';

// This is the class that should be used inside a view which needs to display
// a modal with new content in it.
export class ModalService {
  static inject = [DialogService];
  constructor(dialogService) {
    this.dialogService = dialogService;
  }

  open(modalModel) {
    return this.dialogService.open(modalModel);
  }
}
```

ViewModel that needs to display a modal:

```
//imports

export class Projects {

  // dependency injection
  // constructor
  //...

  createProjectButtonClick() {
    this.modalService.open({
      viewModel: 'accounts/create-project',
      model: { accountId: this.accountId },
    }).then(result => {
      if(result.wasCancelled) {
        return;
      }
      // this.getProjects(this.accountId);
      let router = this.router;
      while (!router.isRoot) {
        router = router.parent;
      }
      router.navigate(this._getProjectHref({id: result.output.id}) + '/settings');
    });
  }
}
```

ViewModel of the modal:

```
// imports

export class CreateProject {
  // dependency injection
  // controller
  // activate()

  save() {
    this.api.command.projects.create(this.createCommand).then(result => {

      if(result.error) {
        console.log('received an error from the API:', result.error);
        // TODO: notify user of error.
        return;
      }

      this.modalController.ok(result);
    });
  }

  cancelButtonClick() {
    // THIS ERRORS AND DOES NOT CLOSE THE MODAL:
    this.modalController.cancel();
  }
}

```

**Comment by m-andrew-albright** [comment] 2016-08-18 01:31
I should mention that the esc key does still work properly.

**Comment by mattbeckman** [comment] 2016-08-23 23:49
+1 on this issue

@m-andrew-albright Were you able to resolve it yourself or is it a legit bug?

**Comment by PWKad** [comment] 2016-08-24 01:23
I'll be digging in to Dialog issues tonight to reproduce, thanks for the sample, and I'll report back here.

**Comment by mattbeckman** [comment] 2016-08-25 00:11
Using "escape" appears to include the injected properties correctly, while, for example, clicking "Cancel" does not. 

State of DialogController when using "Escape":

![screen shot 2016-08-24 at 5 01 49 pm](https://cloud.githubusercontent.com/assets/928380/17952206/16fdb8aa-6a1d-11e6-909b-48d1c244a440.png)

State of DialogController when using "Cancel":

![screen shot 2016-08-24 at 5 03 37 pm](https://cloud.githubusercontent.com/assets/928380/17952209/1d491498-6a1d-11e6-9511-b3ceb6ec1e7f.png)

The errors from DialogController.prototype.close to invokeLifestyle:

![screen shot 2016-08-24 at 5 08 05 pm](https://cloud.githubusercontent.com/assets/928380/17952243/8856819e-6a1d-11e6-8e07-1c9941d48a37.png)

![screen shot 2016-08-24 at 5 03 58 pm](https://cloud.githubusercontent.com/assets/928380/17952218/3b71322a-6a1d-11e6-8c6e-a0f0217ba513.png)

**Comment by m-andrew-albright** [comment] 2016-08-25 00:13
@mattbeckman I temporarily reverted to just directly use the DialogController and DialogService rather than wrapping them - until this issue is fixed.

**Comment by mattbeckman** [comment] 2016-08-25 00:43
It makes sense, I suppose, that the escape key doesn't have a problem, as it's an event bound in the DialogRenderer. However, the Cancel button gets aurelia-binding involved, which is where the injected objects aren't getting wired up properly.

**Comment by mattbeckman** [comment] 2016-08-25 23:06
I found a work around: use the full path of the view model instead of the injected instance.

this.dialogService.open({
	viewModel: "/src/path/to/class/view-models/modal", //this.viewModel,
	model: {}
})

Above appears to work. Obviously, not awesome, but temporary scaffolding until the above issue can be resolved.

**Comment by PWKad** [comment] 2016-08-29 23:58
So the problem appears to be due to some code that I'm not really familiar with and unfortunately it looks like it is also not tested so I'm trying to understand the intended behavior now - 

When clicking close - https://github.com/aurelia/dialog/blob/master/src/dialog-renderer.js#L64

When hitting esc - https://github.com/aurelia/dialog/blob/master/src/dialog-renderer.js#L37

You can see that cancel is called on `top` which appears to be working for you.  I am afraid to start making changes to that code since it is untested but I'll peek in a bit further to see if it starts making sense.

**Comment by m-andrew-albright** [comment] 2016-08-30 00:30
Thanks for the update!

**Comment by mattbeckman** [comment] 2016-08-31 17:13
Issue with my workaround: it doesn't appear to hold on to singleton objects. I thought it was something else, but I'm fairly certain loading from the absolute path won't work when you need singleton behavior.

**Comment by StrahilKazlachev** [comment] 2016-10-09 12:17
I'll use the classes from @m-andrew-albright to explain.
So the problem comes from which container resolves `ModalController`. When `CreateProject` gets resolved, the container which resolves it has a `DialogController` instance registered and can resolve it(the correct instance). When the same container tries to resolve `ModalController` it does not have a resolver registered so it turns to its parent container. In this case it reaches the root which also doesn't have a resolver registered so it calls `.autoRegister(key).get(key)`. This creates an instance of `ModalController` but its dependency `DialogController` also gets resolved from the current container - the root. This is where things break. I'm not sure how to solve this. @PWKad can you advice?

**Comment by mikael-arvidsson** [comment] 2016-11-05 17:14
Any updates on this issue?

**Comment by Infuser** [comment] 2016-12-12 16:43
I would also be interested in hearing progress on this issue

**Comment by PWKad** [comment] 2016-12-13 03:02
Ok I am putting together a repro of the issue now in gist.run.  One thing to note is that the `ModalController` and `ModalService` are basically further abstracting the DialogController and DialogService but I don't see much benefit at the moment.  @StrahilKazlachev was correct in that the issue is in the use of dependency injection as you are not getting the correct instances of everything.  With that being said we'll see if we can provide a way to handle this.

**Comment by PWKad** [comment] 2016-12-13 05:48
Ok to get around the issue you can force the dependency injection system to create a new instance *in the current container* and not move upward in the DI chain looking for a container with the `ModalController`.

```
import {ModalController} from './modal-controller';
import {NewInstance} from 'aurelia-dependency-injection';

export class CreateProject {
  // ..
  static inject = [NewInstance.of(ModalController)];
  constructor(modalController) {
    this.modalController = modalController;
  }
}
```

**Comment by PWKad** [comment] 2016-12-13 05:54
I put together a repro here - https://github.com/PWKad/dialog-repro/blob/master/src/prompt.js#L5 - if this doesn't sufficient answer any of the above questions please let me know, as @StrahilKazlachev mentioned the issue is with DI usage, not necessarily with dialog so going to close this for now.  Feel free to open or ping me to open back up if this doesn't meet the needs identified.  We are having some dialog (pun intended) around this right now as well so it could be transitioned to DI if needed.

**Closed by PWKad** 2016-12-13 05:54 UTC
Labels: bug

**Comment by PWKad** [comment] 2016-12-13 06:39
Ok so to further add to this - we noticed that using the class decorator `@singleton(true)` was not working as intended (based on the docs you can see this is supposed to force all who inject the decorated class to create an instance if not found instead of looking up the chain) so there is an alternative that is even cleaner that should work once this is released - 

https://github.com/aurelia/dependency-injection/commit/98739f245e1d0e98a625f477e21cdc9094f28f60

```
@singleton(true)
export class ModalController {
  // ...
}
```

**Comment by Infuser** [comment] 2016-12-13 10:25
Thanks for looking into this for us Patrick very much appreciated I will give it a go later

**Comment by Infuser** [comment] 2016-12-13 15:04
Turns out my issue was nothing to do with that fix although it raises the same error

I was bringing in my view model and assigning it to the current class
import {BsBrowse} from '../controls/bs-browse';
   constructor(bsBrowse)  {
      this.bsBrowse = bsBrowse;
   }

let response = await this.dialogService.open({viewModel: this.bsBrowse, model: this.person});

This does not work whether it should no idea

Working code
import {BsBrowse} from '../controls/bs-browse';

let response = await this.dialogService.open({viewModel: BsBrowse, model: this.person});

Hopefully this info could help any other new comers to aurelia
