### ISSUE TITLE
the change `dialog-renderer: let click events bubble (6a03bbd)` causes a click event not to be handled by the target

### ISSUE THREAD

**Issue by bebor** [aurelia/dialog#288] opened 2017-05-04 09:47 UTC
**I'm submitting a bug report**

* **Operating System:**
linux 4.10.13-1-ARCH

* **Node Version:**
v7.5.0

* **NPM Version:**
3.8.9
4.1.2

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17
webpack 2.4.1

* **Browser:**
all | Chromium Version 58.0.3029.81 (64-bit)

* **Language:**
all

**Current behavior:**
`
  <ux-dialog class="import-dlg">
    <ux-dialog-body>
     <md-file                    md-on-change.delegate="readFile($event)">>
          </md-file>
     ....
`

**Expected/desired behavior:**
after the change of `ai-dialog` -> `ux-dialog` (https://github.com/aurelia/dialog/commit/6a03bbd) if i click on the file input, all worked fine.
now the click event is not handled by the target. 
tyhe same goes for example for a 1`<md-radio>` tag. i dont think its a `aurelia-materialize-bridge` issue, the same behaviour is if i use `<input type="file"/>` -- it does not open the dialog, (i suppose) because the `event.preventDefault()` is called on the event

P.S. also the examples in your repo, were not updated according to your changelog (https://github.com/aurelia/dialog/tree/master/doc/example -- still use `ai-dialog` instead of `ux-dialog`)

**Comment by StrahilKazlachev** [comment] 2017-05-04 09:57
Duplicate of #281 - awaiting release.

**Closed by StrahilKazlachev** 2017-05-04 09:57 UTC
Labels: duplicate
