### ISSUE TITLE
[dialog-controller] Cancel

### ISSUE THREAD

**Issue by Mordred** [aurelia/dialog#22] opened 2015-08-26 19:54 UTC
`DialogController.cancel()` is not triggering `this._reject`, so that `catch` part of the `dialogService.open()` is never executed.

**Comment by EisenbergEffect** [comment] 2015-08-26 20:00
If I recall, that is by design since closing a dialog shouldn't result in throwing an exception.

**Comment by Mordred** [comment] 2015-08-26 20:23
So there is no way, how to notify parent, that modal was canceled?

**Comment by grischa41277** [comment] 2015-09-02 06:18
Hi there,

I also think it's necessary to call reject...if you want to use the dialogservice e.g. within CanDeactivate of a viewmodel, you may want to return the promise. If reject is never called in the controller, the promise is never handled correctly.

Cheers,
Chris

**Comment by PWKad** [comment] 2015-09-02 17:22
If we call reject and the developer doesn't handle the promise rejection it will throw an error every time.  We thought that would be a bad experience, perhaps we can revisit whether there is a way to do this without throwing the error.  I'm assuming that if we do allow rejection and it throws that the next issue opened will be on that so will be cognizant of that.

**Comment by EisenbergEffect** [comment] 2015-09-02 17:28
Maybe we can return a "promise-like" object with then, catch and cancel chainables?

**Comment by digizen** [comment] 2015-09-10 02:24
If "Cancel" doesn't throw, then the documentation needs to be revised. This is from the docs:

    submit(){
      this.dialogService.open({ viewModel: Prompt, model: 'Good or Bad?'}).then(() =>       
      {
         console.log('good');
      }).catch(() => {
         console.log('bad');
     });

Clicking "OK" prints "good" to the console, but the "bad" clause is never executed, regardless what you click.

**Comment by EisenbergEffect** [comment] 2015-09-10 03:39
@PWKad We definitely need to update the docs, but also what do you think of adding a cancel callback to the promise so that can be used instead of catch when desired? The problem is that rejecting will cause an exception if someone doesn't have a catch handler. We don't want to force that type of api usage, but it could be useful to know when a dialog has been cancelled in some cases, so maybe special api for that?

On that note, I think there may be a proposal for cancellable promises in the works somewhere. We should check on that and if there is, we should adopt that api.

**Comment by digizen** [comment] 2015-09-10 16:55
I think a better approach than cancellable promises is to return a single promise on either "Cancel" or "Ok" events. You can then return an "Result" object as part of the promise that the user can inspect and deal with.

**Comment by EisenbergEffect** [comment] 2015-09-10 19:54
That seems reasonable. So the object my have an `isCanceled` property and an `output` property or something like that. @PWKad What do you think?

**Comment by PWKad** [comment] 2015-09-19 19:43
Sounds good, let me whip something up and see how it looks

**Comment by PWKad** [comment] 2015-09-22 04:21
@digizen @EisenbergEffect I've added this in a `DialogResult` that has two properties - 

```
export class DialogResult {
  wasCancelled = false;
  output;
}
```

This now gets returned on both ok and cancel and populates the output if it was ok.

**Comment by heruan** [comment] 2015-10-19 14:04
I think that resolving with an intermediate `DialogResult` object is very confusing: the returned Promise should resolve only with `ok()` and provide its argument, not with `cancel()`; canceling the dialog is a sort of exception: the `openDialog` promised an action but the user canceled. The developer must handle the rejection and there check if the action was canceled or something bad happened.

**Comment by heruan** [comment] 2016-04-21 14:00
I return on this, since I'm using the plugin extensively and having faced many different scenarios in various apps I'm still very dubious on the `DialogResult` object. In the 90% of use cases, when a user cancels the dialog, nothing needs to be done; instead when she confirms, something needs to be done on a value. So `DialogResult` forces a conditional check where in the 90% of use cases only one branch (the `if (!result.wasCancelled)` one) is needed and meaningful.

I think there are better ways to handle this:
- as @EisenbergEffect suggested, return a cancelable promise-like object (as for http-client's requests);
- let the promise reject on cancel with the proper reason, and make clear on the documentation how the developer can discriminate different rejection reasons.

Is the team still open on discussing this?

**Comment by EisenbergEffect** [comment] 2016-04-21 14:09
I'm open to further discussion of this. I agree. In my experience, you usually don't do anything on cancellation. I would like to find a way to make this simpler. @heruan Can you propose some API ideas here? Some pseudo code so we can look at some ideas and see what we like.

**Comment by jedd-ahyoung** [comment] 2016-04-21 14:23
For what it's worth, I ran into this as well. I'd personally be okay with a regular promise that rejects with a DialogResult or something. Something like this:

    this.dialogService.open(dialogObject)
		.then((result) => {
			return doSomethingAwesome();
		})
		.catch((error) => {
			if (typeof error !== 'DialogCancelled') throw error; // or a duck-type style check, maybe

			// Dialog code here
		});

Optionally, if people decide to use a promise library like Bluebird, they can actually get semantics like this:

	this.dialogService.open(dialogObject)
		.then((result) => {
			return doSomethingAwesome();
		})
		.catch(DialogCancelled, (error) => {
			// Dialog code here - other error types will fall through
		});

**Comment by PWKad** [comment] 2016-04-21 14:34
I'm good with going back to making them catch the errors provided we can include a link to a snippet of exactly what needs to be done to fix it like require.js does.  That would seem like a good preventive measure.

**Comment by EisenbergEffect** [comment] 2016-05-16 13:44
@jedd-ahyoung Let's nail this down once and for all within the next week so we can move this plugin to Beta. Here are a few items we need to make sure work correctly:

* Opening a dialog returns a promise that resolve to the output of the dialog.
* We don't want to throw when there's a cancellation. Developers do need to know when the dialog was closed with a cancellation in some cases.
* After opening the dialog, the consumer needs a way to get access to the dialog controller.

**Comment by jedd-ahyoung** [comment] 2016-07-01 14:52
The last point can be achieved by attaching a reference to the dialog controller on the returned promise. Thus, client code could look like this:

```
var dialogPromise = this.dialogService.open({ ... });
var dialogController = dialogPromise.controller();

dialogPromise.then((dialogResult) => { ... });
```

Not sure if this would cover the use cases we need. There are other possible solutions to this problem (such as storing a dictionary of promises mapped to dialogControlelrs) but they would require a featureset dependency that we don't use (weakmaps).

**Comment by jedd-ahyoung** [comment] 2016-07-01 15:23
The first two points can only be achieved without having an inline branch condition if we use a non-standard promise implementation - something like a `cancelled` method. The API would look like this:

```
this.dialogService.open({ ... })
    .then((dialogResult) => { ... })
    .cancelled((result) => { ... })
    .catch((error) => { ... });
```

@heruan @EisenbergEffect Any thoughts? I'm off today, so I'm taking some time to address some issues.

**Comment by PWKad** [comment] 2016-07-01 15:27
https://github.com/domenic/cancelable-promise#representing-cancelation-the-third-state

currently suggests 

```
this.dialogService.open()
  .cancelCatch()
```
Although it's not entirely stable perhaps if we follow the proposal for now and update later when (if) if it is solidified similar to other proposals.

**Comment by EisenbergEffect** [comment] 2016-07-01 15:28
I think what @PWKad proposes is the best since it's attempting to align with the spec update.

**Comment by EisenbergEffect** [comment] 2016-07-01 16:03
Reconsidering based on conversation with @jdanyow. I'm thinking we should go back to the original api and make promise resolution just represent the closing of the dialog and nothing more. This lets the developer handle "cancellation" however seems best.

**Comment by jedd-ahyoung** [comment] 2016-07-01 21:04
@EisenbergEffect So, effectively, this is a `wontfix` - is that correct? The only thing that will will change is granting access to the dialog controller through the promise object?

**Comment by EisenbergEffect** [comment] 2016-07-01 21:09
I think so. We would shift back to using the promise to represent the closing of the dialog only. We would never call reject. The developer would pass their own result object (whatever they desire) and could use that to track cancellation if they need. We can expose the controller though. The question is how. Would it be better to give the dialog service an api to call to get the controller for a promise? We would keep an internal map, cleaning it out whenever the promise resolved.

**Comment by jedd-ahyoung** [comment] 2016-07-01 22:04
@EisenbergEffect That's initially what I was thinking when I mentioned
weakmaps - we could map promises to controllers. However, we can't create a
dependency on weakmaps. We do already track controllers in the
dialogService, so perhaps we could simply track promises alongside their
controllers within that array.

2016-07-01 17:09 GMT-04:00 Rob Eisenberg <notifications@github.com>:

**Comment by EisenbergEffect** [comment] 2016-07-04 02:18
Yes, please let's do that. I'd like to get this issue closed in the next week if possible.

**Comment by StrahilKazlachev** [comment] 2017-04-28 09:14
The new `rejectOnCancel` setting provides the ability to opt-in to rejecting the promise when canceling. Off by default.

**Closed by StrahilKazlachev** 2017-04-28 09:14 UTC
Labels: enhancement
