### ISSUE TITLE
TypeError: 'self' getter called on an object that does not implement interface Window

### ISSUE THREAD

**Issue by valichek** [aurelia/dialog#32] opened 2015-09-21 09:23 UTC
Using 0.1.1
When I import Prompt from 'aurelia-dialog' all is fine, dialog opens, but when I copy prompt.js and prompt.html to my project I get an error
```
TypeError: 'self' getter called on an object that does not implement interface Window.
Stack trace:
e/</</r.prototype.newModule/</<.get@http://localhost:3030/jspm_packages/system.js:4:10103
get/<@http://localhost:3030/jspm_packages/github/aurelia/metadata@0.7.3/aurelia-metadata.js:132:17
System.forEachModule@http://localhost:3030/jspm_packages/github/aurelia/loader-default@0.9.5/aurelia-loader-default.js:54:13
get@http://localhost:3030/jspm_packages/github/aurelia/metadata@0.7.3/aurelia-metadata.js:130:9
_getViewModel@http://localhost:3030/jspm_packages/github/aurelia/dialog@0.1.1/dialog-service.js:28:33
open/<@http://localhost:3030/jspm_packages/github/aurelia/dialog@0.1.1/dialog-service.js:55:16
Promise@http://localhost:3030/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:193:9
open@http://localhost:3030/jspm_packages/github/aurelia/dialog@0.1.1/dialog-service.js:43:1
askRemove@http://localhost:3030/dist/pages/profiles-index.js:69:1
evaluate@http://localhost:3030/jspm_packages/github/aurelia/binding@0.8.6/aurelia-binding.js:1369:14
bind/this._disposeListener<@http://localhost:3030/jspm_packages/github/aurelia/binding@0.8.6/aurelia-binding.js:5032:22
```

**Comment by PWKad** [comment] 2015-09-22 04:27
Can you please verify this on updated versions of all libraries?  In a pre-beta stage it's not going to be feasible to debug older versions.

**Comment by michaelmalonenz** [comment] 2015-09-23 02:42
I have had issues exactly like this which a conflicting version of core-js.  Once I removed the version I had installed (because of jspm's advice that it wasn't compatible) things started working again.
try `jspm remove core-js` and add a local override (as is in the skeleton app)
```javascript
    "overrides": {
      "npm:core-js@0.9.18": {
        "main": "client/shim.min"
      }
    }
```

and see if that helps.

**Comment by PWKad** [comment] 2015-09-24 03:06
Thanks @michaelmalonenz .  I'm going to close this for now but if someone is able to reproduce on an updated set of libraries please feel free to comment here.

**Closed by PWKad** 2015-09-24 03:06 UTC

**Comment by valichek** [comment] 2015-09-25 10:52
I have updated aurelia libraries but error is still there.
```
TypeError: 'self' getter called on an object that does not implement interface Window.
Stack trace:
e/</</r.prototype.newModule/</<.get@http://localhost:3030/jspm_packages/system.js:4:10103
get/<@http://localhost:3030/jspm_packages/github/aurelia/metadata@0.8.0/aurelia-metadata.js:133:17
System.forEachModule@http://localhost:3030/jspm_packages/github/aurelia/loader-default@0.10.0/aurelia-loader-default.js:94:15
get@http://localhost:3030/jspm_packages/github/aurelia/metadata@0.8.0/aurelia-metadata.js:131:9
_getViewModel@http://localhost:3030/jspm_packages/github/aurelia/dialog@0.3.0/dialog-service.js:28:33
open/<@http://localhost:3030/jspm_packages/github/aurelia/dialog@0.3.0/dialog-service.js:55:16
Promise@http://localhost:3030/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:193:9
open@http://localhost:3030/jspm_packages/github/aurelia/dialog@0.3.0/dialog-service.js:43:1
askRemove@http://localhost:3030/dist/pages/products/loyalty/secuaction/profiles/profiles-index.js:72:13
evaluate@http://localhost:3030/jspm_packages/github/aurelia/binding@0.9.1/aurelia-binding.js:1368:14
bind/this._disposeListener<@http://localhost:3030/jspm_packages/github/aurelia/binding@0.9.1/aurelia-binding.js:5027:22
```

**Comment by PWKad** [comment] 2015-09-25 13:34
@valichek If you can clone the skeleton and reproduce I can try to figure out what the issue you are running in to is.

**Comment by xjdesigns** [comment] 2015-10-23 00:00
I know this appears closed but I ran into this today. @valichek , what version of core-js are you running? My issue was I was using 1.2.2 in my map, and a few other spots. When I changed this back down to what the skeleton uses Dialogs were working in FF. I have not tested this yet in EDGE but all other browsers including IE11 it works.

@PWKad Please mind my lack of full understanding, but I am able to reproduce this issue with the skeleton navigation. It looks to be either A.) and issue with core-js(on my end it was 1.2.2).  B.) having core-js not updated across the board in all locations(package.json and config.js). C.) Me pulling a big nope on implementing option B.

Having these out of sync works in Chrome, Safari, IE11 with no apparent issues.

I bumped all my core-js refs to 0.9.18, which is what is set too in the Skeleton Nav Template.

**Comment by valichek** [comment] 2015-10-23 08:36
@xjdesigns Well, I have __npm:core-js@0.9.18__ as dep for aurelia and __npm:core-js@1.2.1__ as dep for different package (react, fbjs) in my config.js. The exception shows that it is thrown in `core-js@0.9.18/modules/es6.promise.js:193:9 `

**Comment by xjdesigns** [comment] 2015-10-23 09:07
@valichek right I think there is something happening with 1.2.2 for core-js. Does your (react,fbjs) need to use 1.2.2, can you change that back to 0.9.18 and try it out? When changing the dep of the skeleton to using 1.2.2 the dialog throws the exception.

**Comment by sickboy** [comment] 2015-10-23 17:35
0.9.18 works here, 1.2.1 and 1.2.3 break.

**Comment by xjdesigns** [comment] 2015-10-23 17:55
@sickboy Thank you for verifying this. Problems I am running into is the dl-loader throwing `warn` on this being out of date and to update. @PWKad is there anything I can do to help reopen this ticket to look into?
