### ISSUE TITLE
exception "Cannot read property 'removeEventListener' of undefined"

### ISSUE THREAD

**Issue by Leonidnei** [aurelia/dialog#210] opened 2016-09-20 06:42 UTC
I'm getting unhanded exceptions in aurelia-dialog: 

Uncaught (in promise) TypeError: Cannot read property 'removeEventListener' of undefined
    at DialogRenderer.hideDialog (http://localhost/WPL/jspm_packages/npm/aurelia-dialog@1.0.0-beta.3.0.0/dialog-renderer.js:150:26)
    at eval (http://localhost/WPL/jspm_packages/npm/aurelia-dialog@1.0.0-beta.3.0.0/dialog-controller.js:49:36)hideDialog @ dialog-renderer.js:150(anonymous function) @ dialog-controller.js:49
loggingServices.js:41

**Comment by StrahilKazlachev** [comment] 2016-09-20 09:32
Format the issue according to the template and provide a sample/steps to reproduce

**Comment by Leonidnei** [comment] 2016-09-21 05:23
I do not have scenario to reproduce, it happens intermittently.

Can you just add 'if' to to bypass removeEventListener on 'undefined' without full investigation/recreation/etc.?

**Comment by EisenbergEffect** [comment] 2016-09-26 04:37
Closing this issue since it doesn't follow the issue template.

**Closed by EisenbergEffect** 2016-09-26 04:37 UTC
