### ISSUE TITLE
Click off to dismiss

### ISSUE THREAD

**Issue by MarkHerhold** [aurelia/dialog#107] opened 2016-03-08 20:15 UTC
I would like to be able to click on an area outside of the modal to dismiss it when the `lock` option is set to false. This would be similar to the current functionality where the escape key dismisses the dialog.

Are there plans for this/is this something others want as well?

**Comment by PWKad** [comment] 2016-04-20 14:28
Looks like this is a regression from some CSS changes that were merged.

**Comment by PWKad** [comment] 2016-04-20 14:29
Duplicate of #125

**Closed by PWKad** 2016-04-20 14:29 UTC
