### ISSUE TITLE
[BUG] Error thrown and dialogs do not work, when running in node server on Windows OS

### ISSUE THREAD

**Issue by don-bluelinegrid** [aurelia/dialog#213] opened 2016-09-29 19:38 UTC
**I'm submitting a bug report**
- **Library Version:**
  1.0.0-beta.3.0.0

**Please tell us about your environment:**
- **Operating System:**
  OSX 10.5
- **Node Version:**
  4.4.7
- **NPM Version:**
  3.10.3
- **JSPM OR Webpack AND Version**
  webpack 2.1.0-beta.22
- **Browser:**
  all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView
- **Language:**
  TypeScript X.X 

**Current behavior:**

When using aurelia-dialog, with a simple dialog case, an error is thrown and dialogs do not work, when running in node server on Windows OS.  When running node server on Mac OS X or Linux, everything works as expected.

The error is below:

```
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
aurelia-metadata.js:69 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.
bluebird.js:1546 Unhandled rejection Error: Cannot find module './135.html'.
    at webpackContextResolve (http://localhost:9000/app.bundle.js:38598:9)
    at webpackContext (http://localhost:9000/app.bundle.js:38593:29)
    at http://localhost:9000/aurelia-bootstrap.bundle.js:15727:48
From previous event:
    at Promise.then._this2.modulesBeingLoaded.(anonymous function) (http://localhost:9000/aurelia-bootstrap.bundle.js:15726:99)
From previous event:
    at WebpackLoader._import (http://localhost:9000/aurelia-bootstrap.bundle.js:15712:18)
    at WebpackLoader.loadTemplate (http://localhost:9000/aurelia-bootstrap.bundle.js:15776:17)
    at ensureRegistryEntry (http://localhost:9000/aurelia.bundle.js:12369:17)
    at ViewEngine.loadViewFactory (http://localhost:9000/aurelia.bundle.js:12437:12)
    at ConventionalViewStrategy.loadViewFactory (http://localhost:9000/aurelia.bundle.js:9857:23)
    at HtmlBehaviorResource.load (http://localhost:9000/aurelia.bundle.js:13191:27)
    at http://localhost:9000/aurelia.bundle.js:13724:16
From previous event:
    at CompositionEngine.createController (http://localhost:9000/aurelia.bundle.js:13712:69)
    at CompositionEngine._createControllerAndSwap (http://localhost:9000/aurelia.bundle.js:13691:17)
    at CompositionEngine.compose (http://localhost:9000/aurelia.bundle.js:13771:19)
    at http://localhost:9000/app.bundle.js:14949:42
From previous event:
    at http://localhost:9000/app.bundle.js:14944:120
From previous event:
    at _openDialog (http://localhost:9000/app.bundle.js:14940:64)
    at http://localhost:9000/app.bundle.js:14886:14
From previous event:
    at DialogService.open (http://localhost:9000/app.bundle.js:14882:19)
    at CommunityDetail.deleteCommunityMembers (http://localhost:9000/app.bundle.js:11673:28)
    at CallScope.evaluate (http://localhost:9000/aurelia.bundle.js:2951:19)
    at Listener.callSource (http://localhost:9000/aurelia.bundle.js:6392:40)
    at http://localhost:9000/aurelia.bundle.js:6416:22
    at HTMLDocument.handleDelegatedEvent (http://localhost:9000/aurelia.bundle.js:4605:9)
```

This error occurs only on the first time that a dialog is accessed after the page is loaded; subsequent dialog calls do not throw the error, but dialogs are still not shown.

Sample code:

main.ts

```
      .plugin('aurelia-dialog')
```

view.ts

```
  deleteCommunity(community: any) {
    this.dialogService.open({ viewModel: prompt, model: {
        question:this.i18n.tr('community.confirmDelete.title') , 
        message: this.i18n.tr('community.confirmDelete.message', {communityName: community.communityName})
      }
    }).then(response => {
      if (!response.wasCancelled) {
        // Call the delete service.
        console.log('Delete');
      } else {
        // Cancel.
        console.log('Cancel');
      }
    });
  }
```

prompt.ts

```
import {DialogController} from 'aurelia-dialog';

export class Prompt {
  static inject = [DialogController];

  controller: DialogController;
  message: string;
  title: string;

  constructor(controller) {
    this.controller = controller;
    this.title = null;
    this.message = null;

    controller.settings.lock = false;
  }

  activate(model) {
    this.title = model.question;
    this.message = model.message;
  }
}
```

This is very closely adapted from the sample on GitHub.

**Expected/desired behavior:**
Behavior should be the same on Windows OS node server and linux/unix.   There should be no error thrown.

**Comment by StrahilKazlachev** [comment] 2016-09-29 20:09
**I** don't think this is from the dialog(not saying it can not be). I would start with this - ` Unhandled rejection Error: Cannot find module './135.html'.`,  what is, who is requesting it, why can't be found?

**Comment by don-bluelinegrid** [comment] 2016-09-29 20:13
There is no such file, ./135.html.

My assumption is that this is a generated file of some sort.

Here are some facts that I left out of the report:

1. I run node server on WindowsOS and Mac OS X.
2. Until recently, the application worked fine, and consistently, on either platform.
3. After adding aurelia-dialog to the project, I received the error above, only on the WindowsOS platform.
4. No other new files or changes were made; the ./135.html file is not a file from the application project.

**Comment by StrahilKazlachev** [comment] 2016-09-29 20:35
I do remember there **were** some caveats with the dialog and webpack at some point - I don't use webpack so I didn't pay much attention. You could search for some issues in that direction.

**Comment by don-bluelinegrid** [comment] 2016-09-29 20:41
I have been searching for issues for two days, and have wasted a lot of time on this.

The issue doesn't seem specifically related to webpack in general - it is only when running on WindowsOS. 

The only vaguely related issue is this: https://github.com/aurelia/dialog/issues/127
However, that is not the issue that I'm running into, and I did try the suggestion there, which made no difference.

Is aurelia-dialog part of the Aurelia project?  I would expect that the various plugins/modules delivered by the team as "official" Aurelia modues would be tested with the various skeleton projects.  I know that when I log an issue in the main aurelia project, I am always asked to verify/reproduce the issue using a clean installation of a skeleton project.

One of the skeleton projects provided and supported by the Aurelia team is a skeleton-navigation/typescript-webpack project.  If that is supported by the main Aurelia project, then should all aurelia project plugins/modules be compatible with those skeleton projects?

**Comment by EisenbergEffect** [comment] 2016-09-29 20:59
@niieani Can you look into this? Perhaps there's an issue with webpack, maybe even platform specific, that is dropping up when using dialog. It's a plugin that contains html resources, which makes it a bit different than others.

**Comment by don-bluelinegrid** [comment] 2016-09-30 15:10
@EisenbergEffect 

Thanks for assigning this out.
I realize that most of us may be working on Macs/Linux these days - but I happen to be working on a project where our UX team uses WindowsOS - and this dialog issue is popping up consistently.  This is very reproducible with a simple case, just be running a webpack/typescript project in the webpack dev server on a *Windows OS* system.

Don

**Comment by niieani** [comment] 2016-09-30 15:20
`Cannot find module './135.html'` error is pretty odd. I'll need to jump onto my Windows VM to test this. Still pretty busy in the recent days, but I'll see what I can do. The issue is on my ToDo list.

**Comment by StrahilKazlachev** [comment] 2016-09-30 18:46
@don-bluelinegrid We do primarily develop on Win machines and haven't seen this, but we do use SystemJS.

**Comment by goopile** [comment] 2016-10-03 12:15
@niieani Don't know if it helps but I had the same problem when setting up my own project using the aurelia esnext / webpack skeleton. In fact I just ran it and got `Cannot find module './200.html'`.
The name has been random, 67.html, 137.html etc so most likely generated.

Anyhow, I made the dialog work by changing this:
```
import {Prompt} from '../components/prompt';
this.dialog.open({ viewModel: Prompt, model: warning }).then(...
```
into this:
```
this.dialog.open({ viewModel: 'components/prompt', model: warning }).then(...
```
Seemed related so I thought I'd just put this out there in case it gives any clues as to where to start looking.

**Comment by kennyfowler** [comment] 2016-10-19 16:55
i got exactly the same problem when migrating from jspm to webpack. the solution from @goopile didnt work for me right now. will try to reproduce/solve the problem on a fresh skeleton setup...

**Comment by kennyfowler** [comment] 2016-10-19 19:27
ok, i got it to work. @goopile solution did it... i had to use an absolute path:
```
src/main.ts
src/app/dashboard/**dashboard.ts**
src/app/dashboard/modal/**prompt.ts**
```
calling from dashboard.ts
`viewModel: 'app/dashboard/modal/prompt'`

**Comment by PWKad** [comment] 2016-11-09 16:25
This is an issue that is specific to the loader implementation so nothing to fix in dialog so closing for now.

**Closed by PWKad** 2016-11-09 16:25 UTC
Labels: bug
