### ISSUE TITLE
[feature] Ability to define the ai-dialog-overlay and ai-dialog-container parent element

### ISSUE THREAD

**Issue by CedricMalfreytBL** [aurelia/dialog#227] opened 2016-10-28 16:06 UTC
**I'm submitting a feature request**
- **Library Version:**
  1.0.0-beta.3.0.1

**Please tell us about your environment:**
- **Operating System:**
  Windows 7
- **Node Version:**
  6.3.0
  
  
- **NPM Version:**
  3.10.5
  
  
- **JSPM OR Webpack AND Version**
  JSPM 0.16.45
  
  
- **Browser:**
  all
- **Language:**
  TypeScript 2.0.3.0

**Current behavior:**
When opening a dialog, the ai-dialog-overlay and ai-dialog-container elements are created in the body element.

**Expected/desired behavior:**

- **What is the expected behavior?**
  The expected behavior is to be able to choose the element in which the ai-dialog-overlay and ai-dialog-container elements are created, maybe by passing the HTMLElement instance or a selector in the dialogservice.open args.
- **What is the motivation / use case for changing the behavior?**
  I'm developping an application which contains tabs and actually, when a dialog is open, it can't be contextual to a tab.
  The default value for the ai-dialog-overlay and ai-dialog-container parent element could still be 'body' if not provided.

**Comment by PWKad** [comment] 2016-11-09 16:30
Duplicate of #179 fix is described in there

**Closed by PWKad** 2016-11-09 16:30 UTC
Labels: enhancement
