### ISSUE TITLE
Dialog has 100% width in IE11 but not in other browsers

### ISSUE THREAD

**Issue by henning-krause** [aurelia/dialog#91] opened 2016-02-11 09:16 UTC
Started with the skeleton-navigation app and added aurelia-dialog.

Added this import to the top of the welcome.js file:
```js
import {DialogService} from 'aurelia-dialog';
import {Prompt} from 'aurelia-dialog/./examples/prompt';
```

And this submit handler, taken from the Aurelia-Dialog documentation page:

```js
  submit() {
      this.dialogService.open({ viewModel: Prompt, model: 'Good or Bad?'}).then(response => {
      if (!response.wasCancelled) {
        console.log('good');
      } else {
        console.log('bad');
      }
      console.log(response.output);
    });
```

The whole thing works fine in Chrome and Firefox. But in IE11 the dialog has a width of 100%.

Do I have to install any polyfills to get this to work?

**Comment by mbenedyk** [comment] 2016-02-12 09:36
Also if dialog contain buttons they are no clickable - overlay?

**Comment by mbenedyk** [comment] 2016-02-12 11:14
After updating plugin to latest version problem with no clickable buttons seems to be solved, but still dialog in IE 11 has width of 100%

**Comment by JSeligsohn** [comment] 2016-02-25 08:41
The dialog's default styles use width: fit-content. "fit-content" isn't supported in IE browsers... try setting your width for the dialog.

**Comment by PWKad** [comment] 2016-02-25 16:46
@henning-krause @mbenedyk - 

@JSeligsohn is correct.  We have a chore for restyling the dialog for the (hopefully) last time but in the mean time you can set a max-width on your dialog for IE only to work around this issue for the time being.  Leaving this issue open so it is easy to find and we can close it out once the styles are finished.

**Comment by AdamWillden** [comment] 2016-03-15 10:27
@PWKad any ideas when this chore might be completed?

Deciding on whether I should implement a work around, is there a suggested method to use for a work around?

**Comment by AStoker** [comment] 2016-05-06 17:51
-__Bump__- Any update on when this issue will be resolved officially?

**Comment by AdamWillden** [comment] 2016-05-16 15:04
@EisenbergEffect with regards to [your comment here](https://github.com/aurelia/dialog/issues/22#issuecomment-219428140) should a fix for this issue not be considered a priority too?

**Comment by EisenbergEffect** [comment] 2016-05-16 15:06
Yes, it would be nice to have this solved. The fastest way is to submit a PR that address the issue. @jedd-ahyoung can look into it. But if there's a PR, it can get done faster as that takes load of of Jedd. Same goes with any feature or bug. If it's important to you, please let me encourage you to work on a solution with us. That's what open source is about ;)

**Comment by AdamWillden** [comment] 2016-05-18 07:40
I took a moment to look into this. 

[IE does not support the `width: fit-content` CSS used.](http://caniuse.com/#feat=intrinsic-width). In general support for that feature appears to be pretty poor.

I centrally align elements in my application and for that I use the [css transform property](http://caniuse.com/#feat=transforms2d). This does seem to work for the dialog if we were to remove the computed margin-top. However I've not yet found out what happens with oversized dialog content.

All I've tried so far is to replace `ai-dialog{position: relative;` with `ai-dialog{position: absolute;top: 50%;left: 50%;transform: translateX(-50%) translateY(-50%);`.

I'll try looking into this some more at a later date.

**Comment by AdamWillden** [comment] 2016-05-18 07:44
One additional thought is we could detect IE and dynamically add an `ai-dialog-ie` class which provides those overrides and forces margin-top to auto. It would be a poor mans fix but would at least display small dialogs correctly in IE.

Ideally we want a single solution that works across the range I suspect however.

**Comment by EisenbergEffect** [comment] 2016-07-04 14:31
@jedd-ahyoung Status report on this? Has it been addressed?

**Comment by eikaramba** [comment] 2016-07-05 15:08
Update: fit-content does also not work with flex elements inside of its container. It is still highly experimentel, and although i understand to use it, i would rather use fixed percentages instead

**Comment by jedd-ahyoung** [comment] 2016-07-06 00:01
I'm on a Mac, so I can't test this specifically. I haven't had time to look at this. There may, however, be a workaround by using `display: table` as an IE-specific override. I may be able to look into this on my work computer tomorrow.

**Comment by heruan** [comment] 2016-08-02 10:56
I'm also affected by this on a Mac with Chrome using flex. Since when `fit-content` has been introduced, the dialog width doesn't respect the flex directives. Is `fit-content` really necessary?

**Comment by hiscodeness** [comment] 2016-09-14 06:41
Since it is not yet fixed, does anyone have a workaround that I can now use for showing dialogs correctly in IE?

**Comment by a-jackson** [comment] 2016-09-14 08:12
@hiscodeness 
```
ai-dialog {
  display: table !important;
}
```

**Comment by PWKad** [comment] 2016-10-08 15:20
@a-jackson can you confirm this works for all browsers and fixes the width issue?  If so we can make that change to the core styles instead of needing an override.

**Comment by PWKad** [comment] 2016-10-08 15:29
I confirmed it still works in chrome so if someone can give me a thumbs up that it solves the IE issue I can get this in and release on Tuesday.

**Comment by a-jackson** [comment] 2016-10-08 15:31
This worked for us in IE 11. Haven't tested anywhere else.

**Closed** 2016-10-08 19:52 UTC
Labels: renderer

**Comment by codeConcussion** [comment] 2016-10-28 20:58
It looks like fix [d60e234](https://github.com/aurelia/dialog/commit/d60e2346f5458998c388c4d9147bc674dabbc103) broke some dialog layouts for me in Chrome.

I'm using Bootstrap 4 and sizing aurelia dialogs with `col-[size]-[columns]`. If I have a large table I want it to get horizontal scrollbars as the window gets narrower. I'm wrapping them with bootstrap's [`table-responsive`](https://v4-alpha.getbootstrap.com/content/tables/#responsive-tables) class to accomplish that.

Switching the ai-dialog's `display: table` breaks my current dialogs. They won't go smaller that the table's width. Setting it back to `display: block` fixes it again.

I realize this is likely a Bootstrap issue, but my css skills are abysmal, so I thought I'd post here first to see if anyone else is having similar issues.

**Comment by seel93** [comment] 2018-07-24 13:16
This is still an issue for me, even with the solution provided above

**Comment by spapaseit** [comment] 2019-06-20 11:47
What really fixed it for me was adding the following style:

```css
ux-dialog-container {
  > div {
    > div {
        display: table !important;
    }
  }
}
```
