### ISSUE TITLE
controller.cancel(true) close all dialog on page

### ISSUE THREAD

**Issue by taras-krasnytsia** [aurelia/dialog#193] opened 2016-07-22 14:30 UTC
in parent popup dialog i need open new child popup, when child popus is show, after this.controller.cancel(true) only parent popup must be closed, but closed all popups in the page

`import {autoinject} from "aurelia-framework";
import {DialogController, DialogService} from 'aurelia-dialog';

@autoinject
export class ParentTemplate {

  constructor(private dialogService: DialogService, private controller: DialogController) {
    }

 showChildForm() {

            this.dialogService.open({ viewModel: ChildTemplate, model: data });

            this.controller.cancel(true);//must be close only parent popup
    }
}`

**Comment by EisenbergEffect** [comment] 2016-07-22 14:32
@jedd-ahyoung Ping.

**Comment by mbregante** [comment] 2016-07-24 01:16
I have another and maybe related issue. Having child dialogs, on cancel the last dialog is closed as expected but the next one in the chain does nothing when controller.cancel() is called. 
Maybe I do have something strange, but I could not find online examples for nested/child dialogs.

**Comment by jkehler** [comment] 2016-07-25 14:12
I am also experiencing issues with child dialogs. I'm calling the following from within the parent dialog when a send button is clicked.

```
send() {
  this.dialogService.open({
    viewModel: 'path/to/confirm-dialog'
  }).then(resp => {
    if (!resp.wasCancelled) {
      this.controller.ok();
    }
  });
}
```

The problem is that the call to ```this.controller.ok()``` within the parent dialog does not close the dialog after returning from the child dialog. After this happens ```this.controller.cancel()``` also stops working and the parent dialog cannot be closed.

**Comment by simonfox** [comment] 2016-07-25 23:44
@mbregante @jkehler your issue is different to this one but was fixed in #192 you'll just have to wait for the next dialog release as that was only merged recently.

**Comment by davismj** [comment] 2016-07-26 17:34
@simonfox thanks, I had a feeling this was related

**Comment by PWKad** [comment] 2016-10-08 15:31
Fix going out Tuesday.

**Closed by PWKad** 2016-10-08 15:31 UTC
Labels: bug

**Comment by m-andrew-albright** [comment] 2017-01-26 12:02
I am seeing this behavior in the latest version of aurelia-dialog.

I have a large dialog/modal that allows the user to select some items, and upon choosing "delete" our application presents a small confirmation dialog (both of which are aurelia-dialogs).  Upon calling modalController.close() or modalController.ok() from the small confirmation modal, both modals close.

I'm not sure if I should open a new issue in this repo or if this one will be reopened.
