### ISSUE TITLE
"settings.lock = false" does not close dialog when clicking ouside dialog

### ISSUE THREAD

**Issue by jc1001** [aurelia/dialog#74] opened 2015-12-09 12:43 UTC
Hi there,

According to the readme, when the user clicks out of the dialog, it will close and resolve with a cancel.  I can't get this functionality to work (I did confirm that the lock value on the settings object is set to false).  

After some digging in dialog-renderer.js (line 66), I found that there is a click event on the modal overlay that will call the cancel method on the controller when lock is set to false.  The problem is that the modal overlay is rendered behind the modal container (both fill the whole browser window in my application).  From the code (dialog-renderer.js - line 51) I can see that the modal container has a higher z-index than the modal overlay (which basically prevents the click to reach the overlay).  When manually adjusting these values in the browser diagnostic tools, I can get the click event to trigger and close the dialog (basically increased the z-index of the overlay - just as a test).

**Comment by Markusxmr** [comment] 2015-12-09 13:31
:+1:

**Comment by Markusxmr** [comment] 2015-12-09 13:31
:+1:

**Comment by PWKad** [comment] 2015-12-10 17:52
@jc1001 If your dialog is covering the entire window there is no area to click on outside of the dialog correct?  Unless I am mis-understanding your explanation it sounds like that is the case.

Perhaps if you could reproduce the issue and let me know steps to recreate the problem I can help take a look if it is indeed an issue or the intended behavior.

**Comment by jc1001** [comment] 2015-12-11 12:31
Hi there,

Thanks for getting back to me so soon.  I reproduced the issue by doing the following:
* Downloaded the ES2016 starter kit from your site and ran it with the NodeJS option (http-server -o)
* Installed the aurelia-dialog with jspm and added it as a plugin
* Added the edit-person dialog as outlined on the dialog readme.

When I run the sample, I get the following screen:
![dialog1](https://cloud.githubusercontent.com/assets/15125812/11743703/445921f2-a012-11e5-875a-cb47c29562bf.png)

When I use the browser diagnostic tools, I see the following - notice that the highlighting for ai-dialog-overlay and ai-dialog-container both fill the whole screen:
![dialog2](https://cloud.githubusercontent.com/assets/15125812/11743778/e65b91ba-a012-11e5-880f-502914391cd2.png)
![dialog3](https://cloud.githubusercontent.com/assets/15125812/11743780/ea0807da-a012-11e5-9f37-910c6f7315be.png)

Since the click event is bound to the overlay (which has a lower z-index), it is not picked up when clicking outside the visible part of the dialog.

I've attached the solution that I've tested on.
[ES2016.zip](https://github.com/aurelia/dialog/files/59381/ES2016.zip)

Thanks
Julian

**Comment by stsje** [comment] 2015-12-11 15:01
We're experiencing the same issue across multiple dialogs.
Ended up making our own overlay with click handling.

Could be nice to have this issue fixed though :D

**Comment by PWKad** [comment] 2016-01-10 16:05
@benib has a PR to fix this issue that I am going to be merging soon

**Comment by PWKad** [comment] 2016-01-28 00:08
Closed by https://github.com/aurelia/dialog/pull/79

**Closed by PWKad** 2016-01-28 00:08 UTC
Labels: bug
