### ISSUE TITLE
[BUG] Anchor tag crashes dialog

### ISSUE THREAD

**Issue by ogliznutsa** [aurelia/dialog#300] opened 2017-06-15 08:01 UTC
**I'm submitting a bug report**

* **Library Version:**
1.0.0-rc.1.0.3

* **Operating System:**
Windows 10

* **Node Version:**
6.10.3

* **NPM Version:**
3.10.10

* **Webpack Version**
webpack 2.4.1

* **Browser:**
Chrome 58 | Firefox 54

* **Language:**
TypeScript 2.3.4

**Current behavior:**
Tag `<a>` placed inside `<ux-dialog>` crashes dialog - dialog can't be opened, error in console:

> Unhandled rejection RangeError: Maximum call stack size exceeded
    at Container.invoke (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:11778:13)
    at ProviderResolver.get (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:4761:72)
    at Container.get (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:11715:21)
    at Container.elementContainerGet [as get] (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:4816:15)
    at HtmlBehaviorResource.create (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:6782:56)
    at applyInstructions (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:4918:31)
    at ViewFactory.create (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:5139:7)
    at HtmlBehaviorResource.create (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:6794:39)
    at applyInstructions (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:4918:31)
    at ViewFactory.create (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:5139:7)
    at HtmlBehaviorResource.create (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:6794:39)
    at applyInstructions (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:4918:31)
    at ViewFactory.create (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:5139:7)
    at HtmlBehaviorResource.create (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:6794:39)
    at applyInstructions (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:4918:31)
    at ViewFactory.create (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:5139:7)
    at HtmlBehaviorResource.create (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:6794:39)
    at applyInstructions (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:4918:31)
    at ViewFactory.create (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:5139:7)
    at HtmlBehaviorResource.create (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:6794:39)
    at applyInstructions (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:4918:31)
    at ViewFactory.create (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:5139:7)
From previous event:
    at CompositionEngine.createController (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:7241:8)
    at CompositionEngine._createControllerAndSwap (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:7203:17)
    at CompositionEngine.compose (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:7289:19)
    at DialogService.172.DialogService.composeAndShowDialog (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:15218:39)
    at http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:15280:26
From previous event:
    at DialogService.172.DialogService.open (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:15275:12)
    at Register.public/pages/account/register/register.Register.attached (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:101177:28)
    at Controller.attached (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:6212:22)
    at View.attached (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:4272:23)
    at ViewSlot.attached (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:4635:13)
    at View.attached (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:4282:19)
    at ViewSlot.attached (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:4635:13)
    at http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:93787:28
From previous event:
    at Aurelia.setRoot (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:93785:40)
    at Object.<anonymous> (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:97776:50)
    at step (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:97715:23)
    at Object.next (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:97696:53)
    at fulfilled (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:97687:58)
From previous event:
    at step (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:97689:124)
    at http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:97690:9
From previous event:
    at main.__awaiter (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:97686:12)
    at Object.configure (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:97740:12)
    at http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:13570:27
From previous event:
    at config (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:13565:54)
    at http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:13601:12
From previous event:
    at bootstrap (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:13600:24)
    at http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:13587:7
From previous event:
    at run (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:13582:59)
    at Object.<anonymous> (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:13607:16)
    at Object.167 (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:13608:30)
    at __webpack_require__ (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:50:30)
    at Object.351 (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:64798:18)
    at __webpack_require__ (http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:50:30)
    at http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:147:18
    at http://localhost:9000/app.5f1240bb3799e90d8408.bundle.js:150:10

**Comment by abruilo** [comment] 2017-06-15 08:32
I confirm the problem! I faced with it recently.

**Comment by StrahilKazlachev** [comment] 2017-06-15 09:39
Duplicate of #283 - check for details. Source of the issue is tracked in aurelia/templating#549.

**Closed by StrahilKazlachev** 2017-06-15 09:39 UTC
