### ISSUE TITLE
ESC key closes child and parent dialog

### ISSUE THREAD

**Issue by bladegun** [aurelia/dialog#199] opened 2016-07-29 04:48 UTC
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta-3.0.0

* **Browser:**
Chrome, Firefox, Edge, IE 11

**Current behavior:**
I have a parent dialog and a child dialog. When the child dialog is on top of parent dialog, pressing the ESC key closes the child and parent dialog.

**Expected/desired behavior:**
Pressing one ESC key should only close the child (topmost) dialog and not the parent dialog.

**Comment by PWKad** [comment] 2016-08-30 00:07
I'm not sure if this is intended behavior or not so can't really comment yet.  @jedd-ahyoung can you respond on if this is a bug or intended behavior?

**Comment by PWKad** [comment] 2016-09-28 01:05
duplicate of #207 closing this one even though it was opened first because the other description is a little more helpful.  Tracking there.  @bladegun thanks for reporting!

**Closed by PWKad** 2016-09-28 01:05 UTC
