### ISSUE TITLE
DialogController.prototype.close ----- this.viewModel UNDEFINED

### ISSUE THREAD

**Issue by montymccune** [aurelia/dialog#81] opened 2016-01-14 15:39 UTC
On the fourth line, this.viewModel is undefined. The Dialog opens and is rendered correctly, but when I go to close it down, I get the undefined error. I am following the current Dialog examples.

``` javascript
DialogController.prototype.close = function close(ok, result) {
      var _this2 = this;
      var returnResult = new DialogResult(!ok, result);
      return _lifecycle.invokeLifecycle(this.viewModel, 'canDeactivate').then(function (canDeactivate) {
        if (canDeactivate) {
          return _lifecycle.invokeLifecycle(_this2.viewModel, 'deactivate').then(function () {
            return _this2._renderer.hideDialog(_this2).then(function () {
              return _this2._renderer.destroyDialogHost(_this2).then(function () {
                _this2.controller.unbind();
                _this2._resolve(returnResult);
              });
            });
          });
        }
      });
    };
```

**Comment by PWKad** [comment] 2016-01-14 22:04
Did you supply a `ViewModel` property when opening the Dialog?

**Comment by montymccune** [comment] 2016-01-14 22:19
Yes - actually the Modal opens up exactly like I expect it to - with data and everything. When I go to close it however, the this.viewModel error happens in the close event.


On Jan 14, 2016, at 4:04 PM, Patrick Walters <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you supply a ViewModel property when opening the Dialog?

—
Reply to this email directly or view it on GitHub<https://github.com/aurelia/dialog/issues/81#issuecomment-171796367>.




The content of this e-mail message and any attachments are confidential. If you
are not the intended recipient, be advised that any use, dissemination,
distribution, or copying of this e-mail is strictly prohibited.  If you receive
this message in error, please notify the sender immediately by reply e-mail and
destroy the message and its attachments.

**Comment by montymccune** [comment] 2016-01-21 16:44
Thoughts on this?  Again the error occurs here:
```javascript
 DialogController.prototype.close = function close(ok, result) {
      var _this2 = this;

      var returnResult = new DialogResult(!ok, result);
      return _lifecycle.invokeLifecycle(this.viewModel, 'canDeactivate').then(function (canDeactivate) {
        if (canDeactivate) {
          return _lifecycle.invokeLifecycle(_this2.viewModel, 'deactivate').then(function () {
            return _this2._renderer.hideDialog(_this2).then(function () {
              return _this2._renderer.destroyDialogHost(_this2).then(function () {
                _this2.controller.unbind();
                _this2._resolve(returnResult);
              });
            });
          });
        }
      });
    };
```

...on this line: 
return _lifecycle.invokeLifecycle(this.viewModel, 'canDeactivate').then(function (canDeactivate) {

this.viewModel is undefined when it clearly wasn't when it was created due to the fact that my view has repeatable data in it being displayed.

**Comment by PWKad** [comment] 2016-01-22 14:56
Can you create a repro using the basic es6 skeleton?  It would greatly help to see it in action.

**Comment by PWKad** [comment] 2016-01-27 23:50
@montymccune I am unable to reproduce this issue at the moment so a repro is needed to understand the cause.

**Comment by PWKad** [comment] 2016-02-09 02:18
No repro, closing.

**Closed by PWKad** 2016-02-09 02:18 UTC

**Comment by ariovistus** [comment] 2016-06-03 19:50
I just ran into this with v0.6.2. Cursory investigation shows in
https://github.com/aurelia/dialog/blob/master/src/dialog-service.js#L79
```Origin.get``` is returning undefined for my viewmodel.
Now why would it do that? Maybe because I'm using a template someone else put together based on webpack?

I can fix it easily enough by manually sticking it in there:
```js
Origin.set(DialogDemo, new Origin("dialogDemo", "DialogDemo"));
```
but I suspect the framework should be doing this for me somehow. How might I go about making this happen?

**Comment by EisenbergEffect** [comment] 2016-06-03 19:51
It's an issue with Webpack. I'm not sure if it's fixable.

**Comment by ariovistus** [comment] 2016-06-03 19:56
do you have a link to the issue?
