### ISSUE TITLE
Using multiple modals

### ISSUE THREAD

**Issue by RWOverdijk** [aurelia/dialog#67] opened 2015-11-25 09:50 UTC
I might be doing something completely wrong, but I'm having issues with using aurelia-dialog multiple times throughout my application.

### Behavior
What's happening is:

1. I go to page foo, trigger opening a modal: works fine
2. I go to page bar, trigger opening a different modal: It fails with an error (described below)
3. I go back to page foo, trigger opening the modal again, and I get the content of page bar in stead.
4. This behavior now stays the same. The wrong content on page foo, and an error on page bar.

### Technically
I get the following error in the console:

> Unhandled promise rejection Error: No Aurelia APIs are defined for the referenced element.

The code I'm using is simply:

**overview.js:**
```javascript
this.dialogService.open({viewModel: Create}).then(response => {
  if (!response.wasCancelled) {
    this.companies.push(response.output);
  }
});
```

**create-modal.js:**
```javascript
import CompanyEntity from 'entity/company';
import {inject} from 'aurelia-framework';
import {Notification}  from 'service/notification';
import {Router} from 'aurelia-router';
import {DialogController} from 'aurelia-dialog';

@inject(CompanyEntity, Notification, Router, DialogController)
export class Create {

  requestInFlight = false;

  constructor (CompanyEntity, Notification, Router, DialogController) {
    this.notification                             = Notification;
    this.entity                                   = CompanyEntity;
    this.router                                   = Router;
    this.controller                               = DialogController;
    this.controller.settings.lock                 = false;
    this.controller.settings.centerHorizontalOnly = true;
  }

  create () {
    this.requestInFlight = true;

    this.entity.save()
      .then(result => {
        this.requestInFlight = false;
        this.notification.success('Location created successfully');
        this.controller.ok(result);
      })
      .catch(error => {
        console.error(error);
      });
  }
}
```

I'm using the default controller, and as far as I can tell I'm not doing anything _weird_.

**Comment by RWOverdijk** [comment] 2015-11-25 09:57
After debugging a little bit, the element the error is about is one that I define in the template of the modal. This is the create-modal.html:

```html
<template>
  <require from="component/form/company-form"></require>

  <div class="modal form-modal fade in">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 t="Create company"></h4>
        </div>

        <div class="modal-body">
          <company-form view-model.ref="form" data.bind="entity" complete.trigger="create()"></company-form>
        </div>

        <div class="modal-footer">
          <button class="btn btn-sm btn-default" click.trigger="controller.cancel()">
            <span t="Cancel"></span>
          </button>
          <button type="submit" disabled.bind="requestInFlight" click.trigger="form.submit()" class="btn btn-success btn-sm">
            <i if.bind="requestInFlight" class="fa fa-circle-o-notch fa-spin"></i>
            <span t="Create"></span>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
```

It's complaining about the `company-form`. I don't know what this means or how it causes this issue.

**Comment by RWOverdijk** [comment] 2015-11-26 10:07
Another update. It looks like the way these elements are being removed is too aggressive. I still can't figure out where this happens though. I expected it to be on destroy, which probably holds true, but I haven't been able to trace it down to the cause yet.

**Comment by RWOverdijk** [comment] 2015-12-07 16:18
If you could point me in the right direction that'd be great, too. Then I can debug myself.

**Comment by PWKad** [comment] 2015-12-10 18:00
@RWOverdijk Can you create a repro somewhere?  You can clone the dialog repo and repro in the sample app if you want.

**Comment by RWOverdijk** [comment] 2015-12-10 22:28
@PWKad I'll try to do that tomorrow.

**Comment by RWOverdijk** [comment] 2015-12-11 11:08
@PWKad I tried, and found that the error lies in my own code. Could you perhaps help me figure out what it is?

I have the following structure:

page > Modal > Form

The Form ViewModel extends Form (https://github.com/SpoonX/aurelia-form/blob/master/src/form.js). As soon as I remove that (extends Form) it works. But I can't see anything wrong in that file.

**Comment by RWOverdijk** [comment] 2015-12-11 11:43
@PWKad Here's the example project, with the broken state: https://github.com/RWOverdijk/dialog-sample

- Open modal in one
- Navigate to two
- Open modal in two > **Missing content**
- Navigate back to one
- Open modal in one > **Has the content from modal two**

I found the source of the problem, which is code I wrote, but I don't know what the problem is. It can be fixed by removing `extends Form` from the `*-content.js` files. So something in `extends Form`, which is this file: https://github.com/SpoonX/aurelia-form/blob/master/src/form.js is breaking it (and causing very weird behavior).

**Comment by RWOverdijk** [comment] 2015-12-28 13:58
I have worked around this (for now) by not setting the bindables in the parent because I'd otherwise not have made my deadline.. But I'm not happy with it.

Consider this my lengthy bump :)

**Comment by EisenbergEffect** [comment] 2016-01-26 21:43
@RWOverdijk Is this still an issue with the latest?

**Comment by RWOverdijk** [comment] 2016-01-27 15:01
@EisenbergEffect I'll update asap (tomorrow I think) and test.

**Comment by PWKad** [comment] 2016-01-27 23:57
@EisenbergEffect I believe I spoke with @RWOverdijk  spoke of this and the issue is with extending a class with a class that has bindables.  Templating should already be tracking this and I thought it was a do not fix can you confirm this is the case @RWOverdijk

**Comment by EisenbergEffect** [comment] 2016-01-28 00:03
Inheritance is a separate issue we are tracking.

**Comment by RWOverdijk** [comment] 2016-01-28 14:27
@EisenbergEffect I checked, and I'm still getting the same:

> Unhandled promise rejection Error: No Aurelia APIs are defined for the referenced element.(…)

Here's the map for my config related to aurelia:
```js
{
    "aurelia-animator-css": "npm:aurelia-animator-css@1.0.0-beta.1.0.3",
    "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.0.5",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-beta.1.0.2",
    "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.0",
    "aurelia-dialog": "npm:aurelia-dialog@0.5.3",
    "aurelia-fetch-client": "npm:aurelia-fetch-client@1.0.0-beta.1.0.2",
    "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.0.8",
    "aurelia-i18n": "npm:aurelia-i18n@0.4.6",
    "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.1",
    "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.0.1",
    "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.0.3",
    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.0.2",
    "aurelia-validation": "npm:aurelia-validation@0.6.0"
}
```

**Comment by PWKad** [comment] 2016-03-27 12:49
@jedd-ahyoung Fixed by your last feature correct?

**Comment by jedd-ahyoung** [comment] 2016-03-27 15:10
@PWKad This looks like a separate issue entirely. I don't think this has been directly fixed. We can check  latest distribution with the sample that @RWOverdijk has provided and see if the problem still exists, though.

**Comment by RWOverdijk** [comment] 2016-03-30 10:00
@jedd-ahyoung I might be able to test that later today if you want?

**Comment by jedd-ahyoung** [comment] 2016-03-30 13:11
@RWOverdijk If you wouldn't mind. I wanted to take a look at this this week, but I'm preparing for a trip and thus haven't had much time. I'd like to verify that your problem is related to templating and not the dialog itself. The dialog *should* be able to handle multiple windows and controllers without any issues.

**Comment by RWOverdijk** [comment] 2016-03-30 13:13
@jedd-ahyoung I'll see if I can make some time later :)

You're right, I can make multiple windows, just not if they extend from a model that does binding.

**Closed** 2016-05-06 21:38 UTC
