### ISSUE TITLE
Using an Anchor tag inslide a list causes rendering issues

### ISSUE THREAD

**Issue by TonyLugg** [aurelia/dialog#333] opened 2017-11-11 21:30 UTC
**I'm submitting a bug report**

* **Library Version:**
1.0.0-rc.1.0.3

Using CLI with Webpack

* **Browser:**
all

* **Language:**
TypeScript 2.5.3

**Current behavior:**

`            <ul class="vdis-list vdis-track-mouse">
                <li repeat.for="item of listOptions">
                    <a click.delegate="lstOptions_itemSelected(item)">
                        ${item}
                    </a>
                </li> 
            </ul>`

Putting a `<a>` inside the list within the ux-dialog-body causes additional dialogs to be rendered for each item in the list.  Removing the `<a>` and placing the click delegate on the `<li>` eliminates the issue.

**Expected/desired behavior:**

Should be able to use `<a>` in body of dialog.

* **What is the expected behavior?**

Should be able to use `<a>` in body of dialog.

**Comment by StrahilKazlachev** [comment] 2017-11-11 21:36
Closing as duplicate of #283. Feel free to reopen if you think it's different issue.

**Closed by StrahilKazlachev** 2017-11-11 21:36 UTC
